[package]
name = "simd"
version = "0.1.0"
authors = ["Jeron Aldaron Lau <jeronaldaron@gmail.com>"]
edition = "2018"

[dependencies]

[profile.release]
opt-level = 3
panic = 'abort'

[features]
use-simd = []
